// frontend/src/Router.jsx
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import Login from "./pages/Login";
import Player from "./pages/Player";
import Signup from "./pages/Signup";

const MainRouter = () => {
  return <RouterProvider router={router} />;
};

const router = createBrowserRouter([
  { path: "/", element: <Login /> },
  { path: "/signup", element: <Signup /> },
  { path: "/player", element: <Player /> },
]);

export default MainRouter;

// frontend/src/Router.svelte
<script>
    import { Route, Router } from "svelte-routing";
    import Login from "./pages/Login.svelte";
    import Player from "./pages/Player.svelte";
    import Signup from "./pages/Signup.svelte";
</script>

<Router>
    <Route path="/" component={Login} />
    <Route path="/signup" component={Signup} />
    <Route path="/player" component={Player} />
</Router>
